
services:
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    volumes:
      - ./services/auth/src:/app/src
    depends_on:
      - postgres
    secrets:
      - db_password

  game:
    build:
      context: ./services/game
      dockerfile: Dockerfile
    volumes:
      - ./services/game/src:/app/src
    environment:
      - NODE_ENV=development

  chat:
    build:
      context: ./services/chat
      dockerfile: Dockerfile
    volumes:
      - ./services/chat/src:/app/src
    environment:
      - NODE_ENV=development

  user:
    build:
      context: ./services/user
      dockerfile: Dockerfile
    volumes:
      - ./services/user/src:/app/src
    environment:
      - NODE_ENV=development

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      volumes:
        - ./frontend:/app
        - /app/node_modules
      environment:
        - NODE_ENV=development

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - auth
      - game
      - chat
      - user
      - adminer

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: transcendence_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: transcendence_db
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transcendence_user -d transcendence_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - postgres


volumes:
  postgres_data:

secrets:
  db_password:
    file: ./secrets/db_password.txt
